### ISSUE TITLE
English Version?

### ISSUE THREAD

**Issue by lehni** [aliqin/atui#41]
First of all, ATUI looks really good, and is much more lightweight than Element UI. It looks really well designed and considered.

But unfortunately there aren't any locales, currently. Is it planned to support English, and other languages? I would be happy to help out with bringing localisation to the library. I don't speak any Chinese, but I may be able to figure out many of the cases from context / other libraries localisation files.

Apologies to post this here and ignoring the issue guidelines, which are outlined in Chinese.

**Comment by chaoren1641** [comment]
Sorry, it does not support English at present. Due to limited manpower, we have no plan yet, but we welcome community technicians to participate.

Thank you very much for your appreciation of ATUI. There are still many problems to be improved. If it is based on interest research, welcome to develop together. If we just want to use it in the production environment, we recommend the active open source component library such as Element UI.
